# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "public_network"
	
    config.ssh.forward_agent = true

	config.vm.synced_folder "data", '/data'
	config.vm.synced_folder "build", '/build'
	config.vm.synced_folder "src", '/src'

	config.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--memory", "2048"]
	end
	config.vm.provision 'shell', inline: 'ifconfig'

end
